[tool.poetry]
name = "yes"
version = "0.1.0"
description = ""
authors = ["Alena_RA <147716748+Alena-Ryabova@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
